## TODO - finish config
version: "3.7"
services:

    mongo:
        image: mongo:4.2.3
        restart: always
        volumes:
            - "./data:/var/data"
            - ./backup:/var/backup
        command: --dbpath /var/data
        ports:
            - 27017:27017

    webapp:
        image: ${DOCKER_REGISTRY}/tikalk/bookings-client:${BOOKING_DEMO_VERSION}
        ports:
            - '5000:5000'
        depends_on:
            - mongo
            - listings-service

    gql-endpoint:
        image: ${DOCKER_REGISTRY}/tikalk/listings-gql:${BOOKING_DEMO_VERSION}
        ports:
            - '4000:4000'
        depends_on:
            - mongo
        environment:
            - MONGODB_URI='mongodb://mongo:27017'
            - PORT=4000

    listings-service:
        image: ${DOCKER_REGISTRY}/tikalk/listings-service:${BOOKING_DEMO_VERSION}
        ports:
            - '3000:3000'
        depends_on:
            - mongo
        environment:
            - MONGODB_URI='mongodb://mongo:27017'
            - PORT=3000
